scrape_configs:
  - job_name: prometheus_scrapper
    scrape_interval: 5s
    static_configs:
      - targets:
          - locust-exporter:9646
          - locust-exporter-seq:9648

  - job_name: "node"
    scrape_interval: 10s
    scrape_timeout: 5s
    static_configs:
      - targets:
          - master-nodeexporter:9100
  
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
    - targets:
      - cadvisor:8080
