{
 "title": "Locust for Prometheus 2",
 "description": "all locust infos in one page",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Reqeusts",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(locust_requests_current_rps) by (method, path)"
    },
    {
     "expr": "sum(locust_requests_num_requests) by (method, path)"
    },
    {
     "expr": "sum(locust_requests_num_failures) by (method, path)"
    },
    {
     "expr": "sum(locust_requests_avg_response_time) by (method, path)"
    },
    {
     "expr": "sum(locust_requests_max_response_time) by (method, path)"
    }
   ]
  },
  {
   "title": "Transations per sec(Total)",
   "type": "timeseries",
   "description": "tps",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "locust_requests_current_rps{name=\"Aggregated\"}",
     "legendFormat": "Req/s"
    },
    {
     "expr": "locust_requests_current_fail_per_sec{name=\"Aggregated\"}",
     "legendFormat": "Failure/s"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "locust_requests_num_requests{name=\"Aggregated\"}"
    }
   ]
  },
  {
   "title": "Response_time(ms)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "locust_requests_avg_response_time{name=\"Aggregated\"}",
     "legendFormat": "avg_response_time(total)"
    },
    {
     "expr": "locust_requests_median_response_time{name=\"Aggregated\"}",
     "legendFormat": "response_time(median)"
    },
    {
     "expr": "locust_requests_ninetieth_response_time{name=\"Aggregated\"}",
     "legendFormat": "response_time(90%)"
    }
   ]
  },
  {
   "title": "Failed requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "locust_requests_num_failures{name=\"Aggregated\"}"
    }
   ]
  },
  {
   "title": "Slave runners",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "locust_workers_count" }
   ]
  },
  {
   "title": "Failed rate %",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "locust_requests_fail_ratio" }
   ]
  },
  {
   "title": "Num of users",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "locust_users" }
   ]
  },
  {
   "title": "Transations per sec",
   "type": "timeseries",
   "description": "tps",
   "gridPos": { "h": 11, "w": 14, "x": 10, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "locust_requests_current_rps{name!=\"Aggregated\"}",
     "legendFormat": "{{method}}-{{path}}"
    }
   ]
  },
  {
   "title": "Avg_content_length(Total)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "locust_requests_avg_content_length{name=\"Aggregated\"}",
     "legendFormat": "avg_content_length"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "table-old",
   "description": "tps",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(locust_errors) by (method, path, error)"
    }
   ]
  }
 ]
}